config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'destinations#index'
  resources :users, only: [:edit, :update] do
    member do 
      get 'ranking'
    end
  end 
  resources :destinations, only: [:index, :new, :create, :update] do
    collection do 
      get 'recommend'
      post 'recommend'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  
  has_many :user_histories
  has_many :histories, through: :user_histories

  validates :name, presence: true, length: { maximum: 8 }

  def self.history_record(user_histories)
    history_true = user_histories
    history_false = (47 - history_true)
    [{ '訪問済み': history_true, '未訪問': history_false }, history_true]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :move_to_index

  def edit
    @user = current_user
    # 以下はhigh-chartsの記述
    user_histories = @user.histories.count(:id)
    @user_histories, @history_true = User.history_record(user_histories)
  end
  
  def update
    current_user.update(user_params)
    redirect_to edit_user_path(current_user.id)
  end

  def ranking
    # ユーザーに紐づいた訪問数情報を取得して@user_ranks変数に代入する
    @user_history_ranks = User.find(UserHistory.group(:user_id).order('count(history_id) desc').limit(10).pluck(:user_id))
  end

  private

  def user_params
    params.require(:user).permit(history_ids: [])
  end 

  def move_to_index
    unless user_signed_in?
      redirect_to destinations_path
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render "shared/header" %>

<div class="user-main">
  <div class="history-container">
    <h2 class="history-title"><%= current_user.name%>さんの都道府県訪問記録</h2>
    <%= form_with model: @user, url: user_path(@user), method: :patch, local: true do |f| %>

    <%# 以下からhigh-chartsの記述 %>
    <div class="donut-chart">
    <%= pie_chart @user_histories, options = {
        donut: true,  
        colors: ["#1760a0", "rgb(238, 247, 255)"], 
        label: "都道府県数",  
        legend: false, 
        library: {
          title: {
            text: "#{@history_true}/47",  
            align: 'center',  
            verticalAlign: 'middle', 
            style: {
              color: '#1760a0',
              fontWeight: 'bold',
              fontSize: '28px'
            },  
          },
          plotOptions: {
            series: {
              animation: {
                duration: 1400
              }
            },
            pie: {
              dataLabels: {
                enabled: false,  
              },
              size: "110%",
              innerSize: '50%',  
            }
          },
        }
      } %>
    </div>

    <div class="prefecture-check-box">
      <%= f.collection_check_boxes :history_ids, History.all, :id, :name do |history| %>
      <span class="history-details"><%=  history.label {history.check_box + history.text} %></span>
      <% end %>
    </div>
    <div class="update-btn">
      <%= f.submit "UPDATE", class: "update" %>
    </div>
  <% end %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/users/ranking.html.erb
<%= render "shared/header" %>

<div class="ranking-main">
  <div class="ranking-container">
    <h2 class="ranking-title">都道府県訪問数ランキング</h2>
    <table>
      <tr class="tr_top">
        <th>ランク</th>
        <th>ユーザー名</th>
        <th>訪問数</th>
      </tr>
      <% @user_history_ranks.each.with_index(1) do |rank, i| %>
      <% if i == 1 %>
      <tr class="rank1 rank_hover">
        <td><span><%= image_tag("gold_icon.png", class:"crown") %></span><%= i %>位</td>
        <td><%= rank.name %></td>
        <td><%= rank.histories.count %></td> 
      </tr>
      <% elsif i == 2 %>
      <tr class="rank2 rank_hover">
        <td><span><%= image_tag("silver_icon.png", class:"crown") %></span><%= i %>位</td>
        <td><%= rank.name %></td>
        <td><%= rank.histories.count %></td> 
      </tr>
      <% elsif i == 3 %>
      <tr class="rank3 rank_hover">
        <td><span><%= image_tag("blonze_icon.png", class:"crown") %></span><%= i %>位</td>
        <td><%= rank.name %></td>
        <td><%= rank.histories.count %></td> 
      </tr>
      <% else %>
      <tr class="rank_bottom rank_hover">
        <td><%= i %>位</td>
        <td><%= rank.name %></td>
        <td><%= rank.histories.count %></td> 
      </tr>
      <% end %>
      <% end %>
    </table>
    <div class="ranking-btn">
      <%= link_to "BACK", edit_user_path(current_user.id), class:"ranking-button"%>
    </div>
  </div>
</div>

<%= render "shared/footer" %>