config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'destinations#index'
  resources :users, only: [:edit, :update] do
    member do 
      get 'ranking'
    end
  end 
  resources :destinations, only: [:index, :new, :create, :update] do
    collection do 
      get 'recommend'
      post 'recommend'
    end
  end
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class='footer'>
  <div class='footer-contents'>
    <div class='randomtrip-details'>
      <h2 class='footer-content-head'>ABOUT</h2>
      <ul>
        <li><%= link_to 'アプリ概要', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='randomtrip-details'>
      <h2 class='footer-content-head'>SERVICES</h2>
      <ul>
        <% unless user_signed_in? %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "footer-link" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "footer-link" %></li>
        <% end %>
        <li><%= link_to '旅行先診断', new_destination_path, class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <div class='randomtrip-logo'>
    <div class='randomtrip-logo-icon'>
      <%= link_to image_tag("randomtrip_black.png", width:"80", height:"80", class:"logo-black"), "#" %>
    </div>
    <div class='randomtrip-footer-title'>
    <%= link_to "RANDOM TRIP", new_destination_path, class:"randomtrip-letter" %>
    </div>
  </div>
  <div class='copy-right'>
    <p>© RANDOM TRIP</p>
  </div>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='header-contents'>
    <div class='header-left'>
      <div class='lists-left'>
      <%= link_to image_tag("randomtrip_blue.png", width:"80", height:"80", class:"randomtrip-icon"), "/" %>
      </div>
      <div class='header-title'>
        <%= link_to "RANDOM TRIP", "/", class:"randomtrip-letter" %>
      </div>
    </div>
    <nav class='header-right'>
      <ul class='lists-right'>
        <% if user_signed_in? %>
          <li id="accordion_tab" class="link"><%= current_user.name%>さん</li>
          <%# マイページリンク作成 %>
          <ul class="accordion_contents hidden" id="accordion-contents">
          <li><%= link_to '記録', edit_user_path(current_user.id), class: "content" %></li>
          <li><%= link_to 'ランキング', ranking_user_path(current_user.id), class: "content" %></li>
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "content" %></li>
          </ul>
          <li><%= link_to '旅行先診断', new_destination_path, class: "link" %></li>
          <%# マイページリンク作成 %>
        <% else %>
          <li><%= link_to 'ログイン', new_user_session_path, class: "link" %></li>
          <li><%= link_to '新規登録', new_user_registration_path, class: "link" %></li>
          <li><%= link_to '旅行先診断', new_destination_path, class: "link" %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>